### PR TITLE
Fix build with lv2 >= 1.18.0

### LINKED ISSUE #81: _LV2UI_Descriptor invalid conversion compilation error
Similar to https://github.com/openAVproductions/openAV-Fabla/issues/60 I'm getting the following compilation error 
```
[2/49] /usr/bin/x86_64-pc-linux-gnu-g++ -DAVTK_SNDFILE -DFABLA2_DEBUG -DFABLA2_VERSION_STRING="\"v 2.0.0\"" -DHAVE_X11 -DPUGL_HAVE_CAIRO -Dfabla2ui_EXPORTS -I/var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999/src/ui/avtk/avtk -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/libffi/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/uuid -I/usr/include/libpng16  -O2 -pipe -Wall -Wno-sign-compare -g -trigraphs -Wno-unused-function -Wno-unused-variable -Wno-reorder -Wuninitialized -Wl,-z,nodelete -Wl,--no-undefined -fPIC -shared -fPIC -MD -MT CMakeFiles/fabla2ui.dir/src/ui.cxx.o -MF CMakeFiles/fabla2ui.dir/src/ui.cxx.o.d -o CMakeFiles/fabla2ui.dir/src/ui.cxx.o -c /var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999/src/ui.cxx
FAILED: CMakeFiles/fabla2ui.dir/src/ui.cxx.o 
/usr/bin/x86_64-pc-linux-gnu-g++ -DAVTK_SNDFILE -DFABLA2_DEBUG -DFABLA2_VERSION_STRING="\"v 2.0.0\"" -DHAVE_X11 -DPUGL_HAVE_CAIRO -Dfabla2ui_EXPORTS -I/var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999/src/ui/avtk/avtk -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/libffi/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/uuid -I/usr/include/libpng16  -O2 -pipe -Wall -Wno-sign-compare -g -trigraphs -Wno-unused-function -Wno-unused-variable -Wno-reorder -Wuninitialized -Wl,-z,nodelete -Wl,--no-undefined -fPIC -shared -fPIC -MD -MT CMakeFiles/fabla2ui.dir/src/ui.cxx.o -MF CMakeFiles/fabla2ui.dir/src/ui.cxx.o.d -o CMakeFiles/fabla2ui.dir/src/ui.cxx.o -c /var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999/src/ui.cxx
/var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999/src/ui.cxx:442:2: error: invalid conversion from ‘void* (*)(const _LV2UI_Descriptor*, const char*, const char*, LV2UI_Write_Function, LV2UI_Controller, void**, const LV2_Feature* const*)’ {aka ‘void* (*)(const _LV2UI_Descriptor*, const char*, const char*, void (*)(void*, unsigned int, unsigned int, unsigned int, const void*), void*, void**, const LV2_Feature* const*)’} to ‘void* (*)(const LV2UI_Descriptor*, const char*, const char*, LV2UI_Write_Function, LV2UI_Controller, void**, const LV2_Feature* const*)’ {aka ‘void* (*)(const LV2UI_Descriptor*, const char*, const char*, void (*)(void*, unsigned int, unsigned int, unsigned int, const void*), void*, void**, const LV2_Feature* const*)’} [-fpermissive]
  442 |  fabla2_instantiate,
      |  ^~~~~~~~~~~~~~~~~~
      |  |
      |  void* (*)(const _LV2UI_Descriptor*, const char*, const char*, LV2UI_Write_Function, LV2UI_Controller, void**, const LV2_Feature* const*) {aka void* (*)(const _LV2UI_Descriptor*, const char*, const char*, void (*)(void*, unsigned int, unsigned int, unsigned int, const void*), void*, void**, const LV2_Feature* const*)}
```

Full build log
```
cmake -C /var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_GUI=ON -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999_build/gentoo_toolchain.cmake  /var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999
loading initial cache file /var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: x86_64-pc-linux-gnu-pkg-config (found version "1.6.3") 
-- Checking for module 'lv2>=1.8'
--   Found lv2, version 1.18.0
-- Checking for module 'sndfile'
--   Found sndfile, version 1.0.29pre2
-- Checking for module 'samplerate'
--   Found samplerate, version 0.1.9
-- Checking for module 'cairo'
--   Found cairo, version 1.16.0
-- Checking for module 'x11'
--   Found x11, version 1.6.11
-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /usr
Compiler flags:
C               -O2 -pipe -fPIC
C++             -O2 -pipe -Wall -Wno-sign-compare -g -trigraphs -Wno-unused-function -Wno-unused-variable -Wno-reorder -Wuninitialized -Wl,-z,nodelete -Wl,--no-undefined -fPIC -shared
Linker flags:
Executable      -Wl,-O1 -Wl,--as-needed
Module          -Wl,-O1 -Wl,--as-needed
Shared          -Wl,-O1 -Wl,--as-needed

-- Configuring done
-- Generating done
-- Build files have been written to: /var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999_build
>>> Source configured.
>>> Compiling source in /var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999 ...
 * Working in BUILD_DIR: "/var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999_build"
ninja -v -j2 -l0
[1/49] /usr/bin/x86_64-pc-linux-gnu-g++ -DAVTK_SNDFILE -DFABLA2_DEBUG -DFABLA2_VERSION_STRING="\"v 2.0.0\"" -DHAVE_X11 -DPUGL_HAVE_CAIRO -Dfabla2ui_EXPORTS -I/var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999/src/ui/avtk/avtk -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/libffi/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/uuid -I/usr/include/libpng16  -O2 -pipe -Wall -Wno-sign-compare -g -trigraphs -Wno-unused-function -Wno-unused-variable -Wno-reorder -Wuninitialized -Wl,-z,nodelete -Wl,--no-undefined -fPIC -shared -fPIC -MD -MT CMakeFiles/fabla2ui.dir/src/ui/avtk/avtk/box.cxx.o -MF CMakeFiles/fabla2ui.dir/src/ui/avtk/avtk/box.cxx.o.d -o CMakeFiles/fabla2ui.dir/src/ui/avtk/avtk/box.cxx.o -c /var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999/src/ui/avtk/avtk/box.cxx
[2/49] /usr/bin/x86_64-pc-linux-gnu-g++ -DAVTK_SNDFILE -DFABLA2_DEBUG -DFABLA2_VERSION_STRING="\"v 2.0.0\"" -DHAVE_X11 -DPUGL_HAVE_CAIRO -Dfabla2ui_EXPORTS -I/var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999/src/ui/avtk/avtk -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/libffi/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/uuid -I/usr/include/libpng16  -O2 -pipe -Wall -Wno-sign-compare -g -trigraphs -Wno-unused-function -Wno-unused-variable -Wno-reorder -Wuninitialized -Wl,-z,nodelete -Wl,--no-undefined -fPIC -shared -fPIC -MD -MT CMakeFiles/fabla2ui.dir/src/ui.cxx.o -MF CMakeFiles/fabla2ui.dir/src/ui.cxx.o.d -o CMakeFiles/fabla2ui.dir/src/ui.cxx.o -c /var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999/src/ui.cxx
FAILED: CMakeFiles/fabla2ui.dir/src/ui.cxx.o 
/usr/bin/x86_64-pc-linux-gnu-g++ -DAVTK_SNDFILE -DFABLA2_DEBUG -DFABLA2_VERSION_STRING="\"v 2.0.0\"" -DHAVE_X11 -DPUGL_HAVE_CAIRO -Dfabla2ui_EXPORTS -I/var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999/src/ui/avtk/avtk -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/libffi/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/uuid -I/usr/include/libpng16  -O2 -pipe -Wall -Wno-sign-compare -g -trigraphs -Wno-unused-function -Wno-unused-variable -Wno-reorder -Wuninitialized -Wl,-z,nodelete -Wl,--no-undefined -fPIC -shared -fPIC -MD -MT CMakeFiles/fabla2ui.dir/src/ui.cxx.o -MF CMakeFiles/fabla2ui.dir/src/ui.cxx.o.d -o CMakeFiles/fabla2ui.dir/src/ui.cxx.o -c /var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999/src/ui.cxx
/var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999/src/ui.cxx:442:2: error: invalid conversion from ‘void* (*)(const _LV2UI_Descriptor*, const char*, const char*, LV2UI_Write_Function, LV2UI_Controller, void**, const LV2_Feature* const*)’ {aka ‘void* (*)(const _LV2UI_Descriptor*, const char*, const char*, void (*)(void*, unsigned int, unsigned int, unsigned int, const void*), void*, void**, const LV2_Feature* const*)’} to ‘void* (*)(const LV2UI_Descriptor*, const char*, const char*, LV2UI_Write_Function, LV2UI_Controller, void**, const LV2_Feature* const*)’ {aka ‘void* (*)(const LV2UI_Descriptor*, const char*, const char*, void (*)(void*, unsigned int, unsigned int, unsigned int, const void*), void*, void**, const LV2_Feature* const*)’} [-fpermissive]
  442 |  fabla2_instantiate,
      |  ^~~~~~~~~~~~~~~~~~
      |  |
      |  void* (*)(const _LV2UI_Descriptor*, const char*, const char*, LV2UI_Write_Function, LV2UI_Controller, void**, const LV2_Feature* const*) {aka void* (*)(const _LV2UI_Descriptor*, const char*, const char*, void (*)(void*, unsigned int, unsigned int, unsigned int, const void*), void*, void**, const LV2_Feature* const*)}
[3/49] /usr/bin/x86_64-pc-linux-gnu-g++ -DAVTK_SNDFILE -DFABLA2_DEBUG -DFABLA2_VERSION_STRING="\"v 2.0.0\"" -DHAVE_X11 -DPUGL_HAVE_CAIRO -Dfabla2ui_EXPORTS -I/var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999/src/ui/avtk/avtk -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/libffi/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/uuid -I/usr/include/libpng16  -O2 -pipe -Wall -Wno-sign-compare -g -trigraphs -Wno-unused-function -Wno-unused-variable -Wno-reorder -Wuninitialized -Wl,-z,nodelete -Wl,--no-undefined -fPIC -shared -fPIC -MD -MT CMakeFiles/fabla2ui.dir/src/ui/avtk/avtk/button.cxx.o -MF CMakeFiles/fabla2ui.dir/src/ui/avtk/avtk/button.cxx.o.d -o CMakeFiles/fabla2ui.dir/src/ui/avtk/avtk/button.cxx.o -c /var/tmp/portage/media-plugins/fabla-2.9999/work/fabla-2.9999/src/ui/avtk/avtk/button.cxx
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by simonvanderveldt**
Fixes #81

### CODE REVIEW

**Comment by harryhaaren** [comment]
Doh! Sorry @simonvanderveldt  - I've just pushed a minimal fix to master branch... I'll close this now. Thanks for making a PR though!

**Comment by simonvanderveldt** [comment]
;)
`src/ui/avtk/lv2/testUi.cxx` also uses the same `_LV2UI_Descriptor` might be a good idea to fix that as well :)

**Comment by harryhaaren** [comment]
Yep, but that `testUI` isn't build as part of the Fabla2 build process (it is part of the AVTK library, not used by F2). The right place to fix is in https://github.com/openAVproductions/openAV-AVTK and then update the Git Subtree for F2, but AVTK is outdated (superseeded) by https://github.com/openAVproductions/openAV-AVTKA  (note the extra `A` at the end!).

Thanks for being pro-active here - appreciate your bunch of fixes & input to OpenAV over the years!

**Comment by simonvanderveldt** [comment]
Ah, OK. All clear.

> Thanks for being pro-active here - appreciate your bunch of fixes & input to OpenAV over the years!

:+1: Of course, you've created some very nice tools, happy to help where I can :)
Hope all is well. The openAV projects have been pretty quiet for some time.

**Comment by harryhaaren** [comment]
Yep all well  - just occupied doing other fun things in life, and enjoying non-digital things too!

**Comment by simonvanderveldt** [comment]
> Yep all well - just occupied doing other fun things in life, and enjoying non-digital things too!

That's good to hear :) Enjoy!
